### ISSUE TITLE
Zeros truncated in AG data mapping file

### ISSUE THREAD

**Issue by JWDebelius** [biocore/American-Gut#130]
The barcode prefix is truncated from the AG_full.txt map and the AG.txt file.

**Comment by wasade** [comment]
Same with the even1/10k files. Very weird. Good catch, will issue PR tomorrow

**Comment by wasade** [comment]
I know what happened... used excel...

**Comment by ElDeveloper** [comment]
Just so others are aware, AG sample IDs are prone to be interpreted as integers, not only by Excel but also by Pandas, so just be careful.

**Comment by wasade** [comment]
yes, but we have things like "BLANK123.foo.1231" included

**Comment by ElDeveloper** [comment]
Right, AFAIK pandas doesn't require all samples to have the same type,
it is kinda funny in that it infers the type as int even if there's a
few values that cannot be cast.
