### ISSUE TITLE
Mislabeled metadata

### ISSUE THREAD

**Issue by mortonjt** [biocore/American-Gut#146]
Under TYPES_OF_PLANTS, there is a single survey result that entered `28` rather than `21-30`.

Mind if I can submit a PR to fix this.  I'm pretty sure it is an error

**Comment by wasade** [comment]
@mortonjt, can you confirm with @squirrelo as to if this is still an issue in the database? If so, it'd be best to fix this in the database.

**Comment by squirrelo** [comment]
This was fixed in [ag-web#483](https://github.com/biocore/american-gut-web/pull/483)
