### ISSUE TITLE
Generate PNG instead of PDF for per-sample-results

### ISSUE THREAD

**Issue by squirrelo** [biocore/American-Gut#196]
The per sample results script currently generates PDFs for the alpha diversity graphs. These can not be easily shown on the AG webpage. PNG results will be much easier to embed.

**Comment by EmbrietteH** [comment]
Should we also have the option to download a pdf file?

**Comment by squirrelo** [comment]
I was going to have it download the same PNG.

**Comment by JWDebelius** [comment]
I agree with Josh, I think a png is better for most people's uses of individual images. If we decide to embed them in something like a latex document, we may want to go back to PDFs then.

**Comment by wasade** [comment]
PDFs don't embed easily? The advantage is that they're scale-free. Whatever
is easier though. If PNGs, recommend a reasonable DPI
