### ISSUE TITLE
install trouble - conflicting ipython requirements

### ISSUE THREAD

**Issue by cssmillie** [biocore/American-Gut#199]
I'm trying to install americangut, but I run into this error:

> $ sudo python setup.py install --prefix=/home/directory
...
Processing dependencies for americangut==0.0.1
error: ipython 3.2.3 is installed but ipython>=4.0.0 is required by set(['ipykernel'])

But when I install ipython 4.1.1 and re-run the same command, the americangut installer replaces it with ipython 3.2.3. I think this might be because IPython<4.0.0 is listed in the conda requirements.

Any ideas on how to get this installed? Thanks!

**Comment by JWDebelius** [comment]
The requirement has to do with ipymd, which lets your machine parse the markdown files as notebooks. Keep in mind this also requires modifying your ipython config file. Until we sort out how to get ipymd in Jupyter 4.0, the earlier version is required.

I'd recommend using [miniconda](http://conda.pydata.org/miniconda.html) as an environment manager. It's surprisingly easy to use, and lets you have as many versions of files as you want.

**Comment by cssmillie** [comment]
Thanks for the quick response! Sorry, I'm still a little confused. To solve
this problem, what exactly should I do? Thanks again

Chris

**Comment by JWDebelius** [comment]
Hi Chris,

1. Go to http://conda.pydata.org/miniconda.html and install the Python 2.7 version most appropriate for your system. Install it on your system.
2. Navigate to the american gut repository directory. 
3. Create a new conda environment with the command conda create, i.e.
`conda create --name americangut --file conda_requirements.txt`
4. Activate the conda environment (`source activate americangut`)
5. Install the required pip files (`pip install -r pip_requirements.txt`)
6. Install the repository (`pip install . -e --no-deps`)
7. Configure your system for ipymd using the [installation instruction](https://github.com/rossant/ipymd#installation). You will only need to do this once.

**Comment by cssmillie** [comment]
Wow thanks!! Super helpful, I really appreciate it

Chris

**Comment by cssmillie** [comment]
I'm trying to download the American Gut data from EBI, but it looks like
it's missing. Do you know how I can get it? QIITA is a good option, but it
doesn't work for me because I am downloading to a cluster, which is
difficult in QIITA. Thanks!

Chris

**Comment by wasade** [comment]
What accession are you using? The full data are here:

http://www.ebi.ac.uk/ena/data/view/ERP012803

**Comment by iugrina** [comment]
`pip install -r pip_requirements.txt` installs `ipython==4.1.2` with the current version of `pip_requirements.txt`. Since you have `<4.0.0` in `conda_req` could you please add to `pip_req` the exact version needed for the current AG repo (e.g. `IPython>=3.2.1` or `IPython==3.2.1`)

**Comment by wasade** [comment]
Good catch, thanks. Will issue a PR shortly

**Comment by wasade** [comment]
Actually, Im a bit confused, ipython is not specified in directly `pip_requirements.txt`? I do recommend using conda as it does simplify the environment management. 

@JWDebelius, you're primarily using Jupyter > 4.0.0, right?

**Comment by iugrina** [comment]
Yes, I've noticed the differences between conda_req and pip_req (https://github.com/biocore/American-Gut/issues/203).

As for the conda that is not the option for me :( (Python from source + pip + virtualenv)

**Comment by iugrina** [comment]
My questions/comments were resolved with #211
