### ISSUE TITLE
conda_req and pip_req differences

### ISSUE THREAD

**Issue by iugrina** [biocore/American-Gut#203]
Hi,

I'm trying to install americangut and I've stumbled upon some (to me) interesting/strange things. Is there a reason why `pip_requirements.txt` and `conda_requirements.txt` differ (e.g. one contains qiime while other doesn't, cython, IPython, pandas, ...).

**Comment by wasade** [comment]
The intention is for them to be used together (see [.travis.yml](https://github.com/biocore/American-Gut/blob/master/.travis.yml)). Basically, some of the reqs are not available in conda. The preference for conda over pip is that it is much more reliable than pip especially for scipy and matplotlib.

**Comment by iugrina** [comment]
However, if one doesn't use conda he will have problems with installing ag. You should maybe write an INSTALL.md to explain the bootstraping in more details.

**Comment by wasade** [comment]
It's not feasible to support everyones specific environment and our
intention is to support the general case on Linux and OSX. conda is not a
requirement itself, but it greatly simplifies setup of the environment, and
is a standard in the scientific python community. In fact, I think
everything in the pip list has at this point migrated to conda. That being
said, I do agree that having an INSTALL.md would be useful to include in
the repository. We would also be excited for a pull request that would
expand pip support if you're interested in contributing.

**Comment by iugrina** [comment]
Just to be clear, I completely understand that it is not possible to satisfy everyones wishes and I really value the time and effort you've included in making this free and open :+1: 

As for the pip, I'm working on INSTALL.md for Debian 8 (bare), pip, virtenv ;) You'll get the pull request soon I hope :)

**Comment by wasade** [comment]
Ah, that's fantastic! Looking forward to it, and thank you for prodding the code :)

**Comment by iugrina** [comment]
Resolved with commit #211
