### ISSUE TITLE
Contested taxonomy groups should not necessarily show up as rare/unique

### ISSUE THREAD

**Issue by wasade** [biocore/American-Gut#51]
The sample 000004972 has:

k__Bacteria;  p__Bacteroidetes;  c__Bacteroidia;  o__Bacteroidales;  f__[Paraprevotellaceae];  g__[Prevotella];  s__

Showing up as rare, which is misleading.

**Comment by EmbrietteH** [comment]
@wasade can this be closed?

**Comment by wasade** [comment]
I don't believe any code was put in place to address this. Does that sample still show a contested taxon?

**Comment by EmbrietteH** [comment]
That contested taxon does not appear on that participant's current pdf...

**Comment by wasade** [comment]
kk, lets close
