### ISSUE TITLE
Remove any commas from participant's name before creating \yourname{} macro

### ISSUE THREAD

**Issue by cuttlefishh** [biocore/American-Gut#56]
The way the templates are written in LaTeX, having a comma in the user's name, e.g. DALE EARNHARDT, JR., makes the name slightly taller, which pushes some figures onto a second page.  Deleting any commas in the name will avoid this.  Please do for both gut and skin/oral pipelines.

So instead of 

\def\yourname{Dale Earnhardt, Jr.}

the macro should be defined as

\def\yourname{Dale Earnhardt Jr.}

**Comment by jwdebelius** [comment]
This is fixed; we're also not sending the printed results.
