### ISSUE TITLE
test_select_gamma.py fails with ImportError

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/American-Gut#71]
Looks like test_select_gamma.py tries to import from select_gamma.py which only exists under the `scripts` folder. This has to be changed such that the library code that's being tested exists under the `americangut` module. Additionally the test code should not import `select_gamma` as it is currently doing it, it should import:

```python
from americangut.select_gamma import function_name
```

@amnona do you think you could take care of this?

**Comment by jwdebelius** [comment]
This bloom filtering; updated in favor of processing notebooks, and to change in the future in favor of new processing.
